### ISSUE TITLE
Clicking around the bottom of teaTimerFragment or teaInformationFragment opens another teaInformationFragment??

### ISSUE THREAD

**Issue by williamxyshi** [williamxyshi/TeaBuddy#11]
@jane-le what did u do

**Comment by jane-le** [comment]
@williamxyshi lol ..
this is unclear what do u mean

**Comment by williamxyshi** [comment]
@jane-le go to teatimerfragment and click anywhere along the bottom of the screen -> it'll open a tea information fragment 
OR
go into any teainformatiofragment window and click above the brew button -> it'll open another tea information

**Comment by jane-le** [comment]
fixed, fragment hierarchy issue
